### ISSUE TITLE
Build fails if the project has empty javadoc

### ISSUE THREAD

**Issue by LajosCseppento** [LajosCseppento/fancydoc#24]
This causes issues when Fancydoc is applied to all subprojects of a multi-project and some components do not have source code at all.

```
Caused by: java.nio.file.NoSuchFileException: /opt/lcseppen/git/ucap/ucap-core/ucap-common/build/docs/javadoc/src-html
        at dev.lajoscseppento.fancydoc.plugin.impl.LinkSourceSyntaxHighlightAction.rewriteSourceFiles(LinkSourceSyntaxHighlightAction.java:98)
        at dev.lajoscseppento.fancydoc.plugin.impl.LinkSourceSyntaxHighlightAction.applySyntaxHighlighting(LinkSourceSyntaxHighlightAction.java:80)
```

In this build at CERN what happens interestingly (with some internal plugins are applied) that the javadoc task actually runs and does not skip with `NO-SOURCE`

**Comment by LajosCseppento** [comment]
Delivered with 0.2.1 (#26), solution to be confirmed

**Comment by LajosCseppento** [comment]
Fix confirmed
